Repository thoth-station/si-aggregator, pull requests merged in 2020-11, with the labels that each got.

#41 Release of version 0.1.6
  CHANGELOG.md
  app.py
Labels: approved, bot, size/S

#42 port to python 38
  .aicoe-ci.yaml
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#43 update .aicoe-ci.yaml
  .aicoe-ci.yaml
Labels: size/XS
