Repository thoth-station/si-aggregator, pull requests merged in 2020-07, with the labels that each got.

#9 Automatic update of dependency thoth-common from 0.13.13 to 0.14.2
  Pipfile.lock
Labels: approved, bot, size/S

#10 Release of version 0.1.1
  CHANGELOG.md
  app.py
Labels: approved, bot, size/S

#12 include aicoe-ci configuration file
  .aicoe-ci.yaml
  .zuul.yaml
Labels: approved, size/S

#14 add process_data aggregator
  aggregators.py
Labels: approved, size/S

#16 include kevin as a maintainer for project
  .thoth.yaml
Labels: size/XS

#18 Release of version 0.1.2
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS

#19 dependency missing
  Pipfile
  Pipfile.lock
Labels: approved, size/XL

#20 remove flag for 'results_from_file'
  app.py
Labels: approved, size/S
