Repository thoth-station/si-aggregator, pull requests merged in 2020-09, with the labels that each got.

#21 Use new method
  Pipfile.lock
  aggregators.py
Labels: approved, size/L

#23 Automatic update of dependency thoth-common from 0.17.3 to 0.19.0
  Pipfile.lock
Labels: approved, bot

#25 Release of version 0.1.3
  CHANGELOG.md
  app.py
Labels: approved, bot

#26 Add version logs
  app.py
Labels: approved

#28 Release of version 0.1.4
  CHANGELOG.md
  app.py
Labels: approved, bot

#29 make pre-commit happy
  app.py
Labels: approved, size/XS

#30 Adjust env variable CLI
  app.py
Labels: approved, size/XS

#32 Release of version 0.1.5
  CHANGELOG.md
  app.py
Labels: approved, bot, size/XS
