Repository thoth-station/si-aggregator, pull requests merged in 2020-06, with the labels that each got.

#3 Initial si-aggregator cli
  .coafile
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/redeliver_container_image.md
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  README.md
  aggregators.py
  app.py
  template/__init__.py
  template/version.py
Labels: approved, lgtm, size/XL

#5 Automatic update of dependency thoth-common from 0.13.8 to 0.13.12
  Pipfile.lock
Labels: bot, size/XS

#7 Automatic dependency re-locking
  Pipfile.lock
Labels: approved, bot, size/M
